apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "localhost:19092"
  - name: clientID # Optional. Used as client tracing ID by Kafka brokers.
    value: "dapr-kafka-client"
  - name: authRequired # Required.
    value: "false"
  - name: maxMessageBytes # Optional.
    value: 8192